In [3]:
pip install ucimlrepo

Requirement already satisfied: ucimlrepo in .\.venv\lib\site-packages (0.0.7)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: pandas>=1.0.0 in .\.venv\lib\site-packages (from ucimlrepo) (2.3.3)
Requirement already satisfied: certifi>=2020.12.5 in .\.venv\lib\site-packages (from ucimlrepo) (2026.5.20)
Requirement already satisfied: numpy>=1.22.4 in .\.venv\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in .\.venv\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in .\.venv\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2026.2)
Requirement already satisfied: six>=1.5 in .\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)

In [4]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
iris = fetch_ucirepo(id=53) 
  
# data (as pandas dataframes) 
X = iris.data.features 
y = iris.data.targets 
  
# metadata 
print(iris.metadata) 
  
# variable information 
print(iris.variables)

{'uci_id': 53, 'name': 'Iris', 'repository_url': 'https://archive.ics.uci.edu/dataset/53/iris', 'data_url': 'https://archive.ics.uci.edu/static/public/53/data.csv', 'abstract': 'A small classic dataset from Fisher, 1936. One of the earliest known datasets used for evaluating classification methods.\n', 'area': 'Biology', 'tasks': ['Classification'], 'characteristics': ['Tabular'], 'num_instances': 150, 'num_features': 4, 'feature_types': ['Real'], 'demographics': [], 'target_col': ['class'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1936, 'last_updated': 'Tue Sep 12 2023', 'dataset_doi': '10.24432/C56C76', 'creators': ['R. A. Fisher'], 'intro_paper': {'ID': 191, 'type': 'NATIVE', 'title': 'The Iris data set: In search of the source of virginica', 'authors': 'A. Unwin, K. Kleinman', 'venue': 'Significance, 2021', 'year': 2021, 'journal': 'Significance, 2021', 'DOI': '1740-9713.01589', 'URL': 'https://www.semanticscholar.org/paper/4599862ea877863669a6a8e63a3c707a787d5d7e', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': 'This is one of the earliest datasets used in the literature on classification methods and widely used in statistics and machine learning.  The data set contains 3 classes of 50 instances each, where each class refers to a type of iris plant.  One class is linearly separable from the other 2; the latter are not linearly separable from each other.\n\nPredicted attribute: class of iris plant.\n\nThis is an exceedingly simple domain.\n\nThis data differs from the data presented in Fishers article (identified by Steve Chadwick,  spchadwick@espeedaz.net ).  The 35th sample should be: 4.9,3.1,1.5,0.2,"Iris-setosa" where the error is in the fourth feature. The 38th sample: 4.9,3.6,1.4,0.1,"Iris-setosa" where the errors are in the second and third features.  ', 'purpose': 'N/A', 'funded_by': None, 'instances_represent': 'Each instance is a plant', 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': None, 'citation': None}}
           name     role         type demographic  \
0  sepal length  Feature   Continuous        None
1   sepal width  Feature   Continuous        None
2  petal length  Feature   Continuous        None
3   petal width  Feature   Continuous        None
4         class   Target  Categorical        None

                                         description units missing_values
0                                               None    cm             no
1                                               None    cm             no
2                                               None    cm             no
3                                               None    cm             no
4  class of iris plant: Iris Setosa, Iris Versico...  None             no

In [11]:
y

              class
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 1 columns]

In [64]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.8,random_state=1)

In [65]:
from sklearn.ensemble import RandomForestClassifier
CLF_L = RandomForestClassifier()
CLF_L.fit(x_train,y_train)

e:\code\datascience\plot\.venv\ml\ML_Prog\.venv\lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestClassifier()

In [66]:
predict = CLF_L.predict(x_test)

In [67]:
import pandas as pd
import numpy as np
test_case = pd.DataFrame()
test_case['Actual'] = y_test
test_case['predict'] = predict

In [68]:
test_case

              Actual          predict
14       Iris-setosa      Iris-setosa
98   Iris-versicolor  Iris-versicolor
75   Iris-versicolor  Iris-versicolor
16       Iris-setosa      Iris-setosa
131   Iris-virginica   Iris-virginica
..               ...              ...
3        Iris-setosa      Iris-setosa
142   Iris-virginica   Iris-virginica
30       Iris-setosa      Iris-setosa
147   Iris-virginica   Iris-virginica
106   Iris-virginica  Iris-versicolor

[120 rows x 2 columns]

In [69]:
count = 0
# for i in range(0,len(test_case)):
#     if test_case['Actual'].iloc[i]==test_case['predict'].iloc[i]:

for actual, predict in zip(test_case['Actual'], test_case['predict']):
    if actual == predict:
        count = count +1

accuracy = (count/len(test_case)) * 100
print(accuracy)

90.83333333333333

In [70]:
from sklearn.gaussian_process import GaussianProcessClassifier
CLF_L = GaussianProcessClassifier()
CLF_L.fit(x_train,y_train)

e:\code\datascience\plot\.venv\ml\ML_Prog\.venv\lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GaussianProcessClassifier()

In [74]:
predict_2 = CLF_L.predict(x_test)
test_case2 = pd.DataFrame()
test_case2['Actual'] = y_test
test_case2['predict'] = predict_2

In [75]:
cnt=0
for actual, predict in zip(test_case2['Actual'], test_case2['predict']):
    if actual == predict:
        cnt = cnt +1

accuracy_2 = (cnt/len(test_case2)) * 100
print(accuracy_2)

92.5